"""Add created_by to Quiz model

Revision ID: 5667abfd68fe
Revises: ceead48310f8
Create Date: 2024-12-27 12:02:46.609635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5667abfd68fe'
down_revision = 'ceead48310f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('time_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_quiz_created_by_user', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_created_by_user', type_='foreignkey')
        batch_op.alter_column('time_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
